[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20" # O la versión de Node que estés usando localmente

[context.production.environment]
  NODE_ENV = "production"
